// Extended service details for individual service pages

export interface ServiceDetail {
  id: string
  category: string
  title: string
  fullTitle: string
  description: string
  longDescription: string
  image: string
  features: string[]
  benefits: string[]
  process: { step: number; title: string; description: string }[]
  faqs: { question: string; answer: string }[]
}

export const RESIDENTIAL_SERVICE_DETAILS: Record<string, ServiceDetail> = {
  'appliance-wiring': {
    id: 'appliance-wiring',
    category: 'Wiring',
    title: 'Appliances',
    fullTitle: 'Appliance Wiring Services',
    description: 'We provide professional appliance wiring solutions, experience the ultimate connection.',
    longDescription: 'Modern homes rely on a variety of electrical appliances that require proper wiring for safe and efficient operation. Our licensed electricians specialize in appliance wiring installation, ensuring your refrigerators, ovens, dryers, washers, and other major appliances are connected safely to your electrical system. We handle everything from 240V outlet installations to dedicated circuit wiring for high-power appliances.',
    image: '/images/Appliances-Service-Image.webp',
    features: [
      '240V outlet installation for heavy appliances',
      'Dedicated circuit wiring',
      'GFCI protection for kitchen appliances',
      'Dryer and washer hookups',
      'Oven and range wiring',
      'Refrigerator circuit installation',
      'Dishwasher electrical connections',
      'Garbage disposal wiring',
    ],
    benefits: [
      'Ensures appliance safety and longevity',
      'Prevents electrical fires and hazards',
      'Meets all local electrical codes',
      'Improves energy efficiency',
      'Provides proper voltage for optimal performance',
    ],
    process: [
      { step: 1, title: 'Assessment', description: 'We evaluate your electrical panel capacity and appliance requirements.' },
      { step: 2, title: 'Planning', description: 'We design the optimal wiring solution for your specific appliances.' },
      { step: 3, title: 'Installation', description: 'Our licensed electricians install all wiring and outlets to code.' },
      { step: 4, title: 'Testing', description: 'We thoroughly test all connections for safety and proper function.' },
    ],
    faqs: [
      { question: 'Do I need a dedicated circuit for my appliances?', answer: 'Yes, most major appliances like refrigerators, ovens, dryers, and washers require dedicated circuits to operate safely and efficiently.' },
      { question: 'Can you install a 240V outlet for my dryer?', answer: 'Absolutely. We specialize in 240V outlet installations for dryers, ovens, and other high-power appliances.' },
      { question: 'How long does appliance wiring take?', answer: 'Most appliance wiring projects can be completed in 2-4 hours, depending on the complexity and accessibility.' },
    ],
  },
  'breaker-replacement': {
    id: 'breaker-replacement',
    category: 'Residential',
    title: 'Breakers Replacement',
    fullTitle: 'Residential Breaker Replacement',
    description: 'Our team of professionals is equipped to ensure your home\'s safety with our reliable residential breaker replacement services.',
    longDescription: 'Circuit breakers are the first line of defense in protecting your home from electrical fires and damage. When breakers become old, worn, or start tripping frequently, it\'s time for replacement. Our expert electricians provide fast, reliable breaker replacement services to keep your home\'s electrical system safe and functioning properly. We work with all major brands and panel types.',
    image: '/images/Residential-Breakers-Replacement-Service-Image.webp',
    features: [
      'Single and double-pole breaker replacement',
      'AFCI and GFCI breaker installation',
      'Panel inspection and assessment',
      'Brand matching for existing panels',
      'Emergency breaker replacement',
      'Whole-panel breaker upgrades',
      'Obsolete breaker replacement',
      'Load balancing optimization',
    ],
    benefits: [
      'Eliminates frequent tripping issues',
      'Prevents electrical fires',
      'Improves electrical system reliability',
      'Meets current safety codes',
      'Extends panel lifespan',
    ],
    process: [
      { step: 1, title: 'Diagnosis', description: 'We identify the problem breaker and assess overall panel condition.' },
      { step: 2, title: 'Selection', description: 'We source the correct replacement breaker for your specific panel.' },
      { step: 3, title: 'Replacement', description: 'Our electrician safely replaces the faulty breaker.' },
      { step: 4, title: 'Verification', description: 'We test the new breaker and entire circuit for proper operation.' },
    ],
    faqs: [
      { question: 'Why does my breaker keep tripping?', answer: 'Frequent tripping can indicate an overloaded circuit, a short circuit, a ground fault, or a failing breaker that needs replacement.' },
      { question: 'How do I know if my breaker needs replacement?', answer: 'Signs include frequent tripping, visible damage, burning smell, breaker won\'t stay on, or the breaker is over 20 years old.' },
      { question: 'Can I replace a breaker myself?', answer: 'Breaker replacement should only be done by a licensed electrician due to the serious safety risks involved with working in electrical panels.' },
    ],
  },
  'ceiling-fan': {
    id: 'ceiling-fan',
    category: 'Installation',
    title: 'Ceiling Fan',
    fullTitle: 'Ceiling Fan Installation',
    description: 'Take advantage of our expert ceiling fan installers: efficient, safe, reliable, professional, customer-focused.',
    longDescription: 'Ceiling fans are an excellent way to improve comfort and reduce energy costs in your home. Our professional ceiling fan installation service ensures your fans are mounted securely, wired correctly, and balanced perfectly. Whether you\'re replacing an existing fan, converting a light fixture to a fan, or installing in a new location, our electricians handle it all with precision and care.',
    image: '/images/Residential-Ceiling-Fan-Service-Image.webp',
    features: [
      'New ceiling fan installation',
      'Fan replacement and upgrades',
      'Light kit additions',
      'Remote control setup',
      'Smart fan installation',
      'Outdoor fan installation',
      'High ceiling installations',
      'Fan balancing and adjustment',
    ],
    benefits: [
      'Reduces energy costs by up to 40%',
      'Improves air circulation year-round',
      'Adds value to your home',
      'Enhances room comfort',
      'Provides additional lighting options',
    ],
    process: [
      { step: 1, title: 'Consultation', description: 'We help you choose the right fan size and style for your space.' },
      { step: 2, title: 'Preparation', description: 'We ensure proper electrical box support and wiring.' },
      { step: 3, title: 'Installation', description: 'Our team securely mounts and wires your new ceiling fan.' },
      { step: 4, title: 'Balancing', description: 'We balance the blades and test all functions for smooth operation.' },
    ],
    faqs: [
      { question: 'Can you install a ceiling fan where there\'s only a light fixture?', answer: 'Yes, we can convert most light fixture locations to accommodate a ceiling fan, including upgrading the electrical box if needed.' },
      { question: 'What size ceiling fan do I need?', answer: 'Fan size depends on room size: 29-36" for rooms up to 75 sq ft, 36-42" for 76-144 sq ft, 44-52" for 144-225 sq ft, and 52-60" for larger rooms.' },
      { question: 'Do you install outdoor ceiling fans?', answer: 'Yes, we install damp-rated and wet-rated ceiling fans for covered patios, porches, and outdoor living spaces.' },
    ],
  },
  'code-corrections': {
    id: 'code-corrections',
    category: 'Residential',
    title: 'Code Corrections',
    fullTitle: 'Residential Electrical Code Corrections',
    description: 'Our Electricians ensure safety, compliance, and reliability through expert wiring code corrections.',
    longDescription: 'Electrical codes exist to protect your family and property from electrical hazards. Whether you\'re selling your home, dealing with insurance requirements, or simply want to ensure your electrical system is safe, our code correction services bring your home up to current standards. We identify violations, explain the issues, and perform all necessary repairs to achieve full compliance.',
    image: '/images/Residentail-code-Corrections-Service-Image.webp',
    features: [
      'Complete electrical inspections',
      'Code violation identification',
      'GFCI/AFCI upgrades',
      'Grounding corrections',
      'Panel labeling and organization',
      'Junction box covers and repairs',
      'Wire gauge corrections',
      'Permit acquisition assistance',
    ],
    benefits: [
      'Ensures home safety',
      'Satisfies insurance requirements',
      'Facilitates home sales',
      'Prevents electrical fires',
      'Provides peace of mind',
    ],
    process: [
      { step: 1, title: 'Inspection', description: 'We perform a thorough inspection of your entire electrical system.' },
      { step: 2, title: 'Report', description: 'We provide a detailed report of all code violations found.' },
      { step: 3, title: 'Correction', description: 'Our team performs all necessary repairs and upgrades.' },
      { step: 4, title: 'Certification', description: 'We arrange for final inspection and provide documentation.' },
    ],
    faqs: [
      { question: 'What are common electrical code violations?', answer: 'Common violations include missing GFCI outlets in wet areas, improper grounding, overcrowded panels, exposed wiring, and missing junction box covers.' },
      { question: 'Do I need code corrections to sell my home?', answer: 'Many home inspectors will flag code violations, and buyers often require corrections before closing. It\'s wise to address issues proactively.' },
      { question: 'How much do code corrections cost?', answer: 'Costs vary depending on the number and severity of violations. We provide detailed quotes after inspection.' },
    ],
  },
  'rewiring': {
    id: 'rewiring',
    category: 'Residential',
    title: 'Rewiring',
    fullTitle: 'Whole-House Rewiring',
    description: 'We offer comprehensive home electrical system re-wires and upgrades for safety, efficiency, and modernization.',
    longDescription: 'Homes built before the 1970s often have outdated wiring that can\'t handle modern electrical demands and may pose safety risks. Our whole-house rewiring service replaces old, dangerous wiring with modern, code-compliant electrical systems. We minimize disruption to your home while ensuring every outlet, switch, and fixture is properly connected to a safe, reliable electrical system.',
    image: '/images/Residential-Rewiring-Service-Image.webp',
    features: [
      'Complete house rewiring',
      'Knob and tube replacement',
      'Aluminum wiring replacement',
      'Panel upgrades included',
      'New outlet and switch installation',
      'Dedicated circuits for modern needs',
      'Whole-house surge protection',
      'Smart home pre-wiring',
    ],
    benefits: [
      'Eliminates fire hazards from old wiring',
      'Supports modern electrical demands',
      'Increases home value',
      'Reduces insurance costs',
      'Enables smart home technology',
    ],
    process: [
      { step: 1, title: 'Assessment', description: 'We evaluate your current wiring and create a comprehensive plan.' },
      { step: 2, title: 'Permitting', description: 'We handle all permits and coordinate inspections.' },
      { step: 3, title: 'Installation', description: 'Our team systematically replaces all wiring with minimal disruption.' },
      { step: 4, title: 'Completion', description: 'We restore walls, test everything, and obtain final inspection approval.' },
    ],
    faqs: [
      { question: 'How long does a whole-house rewire take?', answer: 'Most homes can be rewired in 3-7 days, depending on size and complexity. We work efficiently to minimize disruption.' },
      { question: 'Do I need to move out during rewiring?', answer: 'In most cases, no. We work room by room and maintain power to essential areas throughout the project.' },
      { question: 'How do I know if my home needs rewiring?', answer: 'Signs include frequent breaker trips, flickering lights, burning smells, discolored outlets, or if your home has knob-and-tube or aluminum wiring.' },
    ],
  },
  'outdoor-lighting': {
    id: 'outdoor-lighting',
    category: 'Outdoor',
    title: 'Lighting',
    fullTitle: 'Outdoor Lighting Installation',
    description: 'We know outdoor wiring like the back of our hand. Trust us to get the job done right, on time and on budget.',
    longDescription: 'Transform your outdoor spaces with professional lighting installation from Westek Electric. From security floodlights to elegant patio string lights, we design and install outdoor lighting systems that enhance safety, security, and curb appeal. Our weatherproof installations are built to withstand the elements while providing reliable illumination for years to come.',
    image: '/images/Outdoor-Lighting-Service-Image.webp',
    features: [
      'Security and flood lighting',
      'Patio and deck lighting',
      'Pathway and walkway lights',
      'Motion sensor installation',
      'Dusk-to-dawn lighting',
      'Outdoor outlet installation',
      'Weatherproof connections',
      'Smart outdoor lighting controls',
    ],
    benefits: [
      'Enhances home security',
      'Increases curb appeal',
      'Extends outdoor living hours',
      'Improves safety on walkways',
      'Adds property value',
    ],
    process: [
      { step: 1, title: 'Design', description: 'We create a custom lighting plan for your outdoor spaces.' },
      { step: 2, title: 'Preparation', description: 'We run weatherproof wiring and install proper circuits.' },
      { step: 3, title: 'Installation', description: 'Our team installs all fixtures and controls.' },
      { step: 4, title: 'Programming', description: 'We set up timers, sensors, and smart controls to your preferences.' },
    ],
    faqs: [
      { question: 'What type of outdoor lighting is best for security?', answer: 'Motion-activated floodlights and dusk-to-dawn fixtures are most effective for security, covering entry points and dark areas.' },
      { question: 'Are outdoor lights energy efficient?', answer: 'Yes, we primarily install LED outdoor lighting which uses 75% less energy than traditional bulbs and lasts much longer.' },
      { question: 'Can outdoor lights be connected to smart home systems?', answer: 'Absolutely. We can install smart outdoor lighting that you control from your phone or integrate with systems like Alexa or Google Home.' },
    ],
  },
  'indoor-lighting': {
    id: 'indoor-lighting',
    category: 'Indoor',
    title: 'Lighting',
    fullTitle: 'Indoor Lighting Installation',
    description: 'Westek offers professional indoor wiring services for homes and businesses. Schedule a consultation today.',
    longDescription: 'The right lighting transforms your living spaces, enhancing both functionality and ambiance. Our indoor lighting experts install everything from recessed can lights and chandeliers to under-cabinet LEDs and smart lighting systems. We work with you to create layered lighting designs that meet your practical needs while reflecting your personal style.',
    image: '/images/Indoor_Lighting-Service-Image.webp',
    features: [
      'Recessed lighting installation',
      'Chandelier and pendant mounting',
      'Under-cabinet lighting',
      'Dimmer switch installation',
      'Track and rail lighting',
      'LED retrofit and upgrades',
      'Smart lighting systems',
      'Accent and task lighting',
    ],
    benefits: [
      'Improves home ambiance',
      'Reduces energy costs with LEDs',
      'Increases home value',
      'Enhances task visibility',
      'Creates custom atmospheres',
    ],
    process: [
      { step: 1, title: 'Consultation', description: 'We discuss your lighting goals and assess your spaces.' },
      { step: 2, title: 'Design', description: 'We create a lighting plan that balances function and style.' },
      { step: 3, title: 'Installation', description: 'Our electricians install all fixtures with minimal mess.' },
      { step: 4, title: 'Fine-tuning', description: 'We adjust positioning and set up controls to your preferences.' },
    ],
    faqs: [
      { question: 'How many recessed lights do I need?', answer: 'A general rule is one recessed light per 4-6 square feet of ceiling space, but this varies based on ceiling height and desired brightness.' },
      { question: 'Can you add lights without running new wires?', answer: 'Sometimes yes, using existing circuits. However, for optimal safety and function, new dedicated circuits are often recommended.' },
      { question: 'What\'s the benefit of dimmer switches?', answer: 'Dimmers extend bulb life, save energy, and let you adjust ambiance for different activities and times of day.' },
    ],
  },
  'pool-spa-lighting': {
    id: 'pool-spa-lighting',
    category: 'Repair',
    title: 'Pool & Spa Lighting',
    fullTitle: 'Pool & Spa Lighting Services',
    description: 'Our wiring professionals ensure safe expert pool, spa, and jacuzzi lighting for your backyard oasis.',
    longDescription: 'Pool and spa lighting requires specialized expertise due to the unique safety requirements of water and electricity. Our licensed electricians are trained in the specific codes and best practices for underwater and poolside lighting. We install, repair, and upgrade pool lights, spa lights, and surrounding landscape lighting to create a safe, beautiful aquatic environment.',
    image: '/images/Pool_Lighting-Service-Image.webp',
    features: [
      'Underwater LED pool lights',
      'Spa and hot tub lighting',
      'Color-changing pool lights',
      'Pool deck lighting',
      'GFCI protection installation',
      'Low-voltage lighting systems',
      'Light repair and replacement',
      'Automation and controls',
    ],
    benefits: [
      'Extends pool usage into evening',
      'Enhances safety around water',
      'Creates stunning visual effects',
      'Increases property value',
      'Meets strict safety codes',
    ],
    process: [
      { step: 1, title: 'Safety Assessment', description: 'We evaluate existing electrical systems and bonding/grounding.' },
      { step: 2, title: 'Planning', description: 'We design a lighting plan that meets codes and your vision.' },
      { step: 3, title: 'Installation', description: 'Our team installs all lighting with proper waterproofing and GFCI protection.' },
      { step: 4, title: 'Testing', description: 'We thoroughly test all systems for safety and proper operation.' },
    ],
    faqs: [
      { question: 'Are LED pool lights worth the upgrade?', answer: 'Yes, LED pool lights use 75% less energy, last 10+ years, and offer color-changing options not available with incandescent lights.' },
      { question: 'How often should pool lights be inspected?', answer: 'Pool electrical systems should be inspected annually to ensure all safety features are functioning properly.' },
      { question: 'Can you fix a pool light that\'s not working?', answer: 'Yes, we diagnose and repair pool lighting issues including bulb replacement, seal repairs, and wiring problems.' },
    ],
  },
  'hot-tub-spa-pool-jacuzzi': {
    id: 'hot-tub-spa-pool-jacuzzi',
    category: 'Wiring',
    title: 'Hot Tub, Spa, Pool & Jacuzzi',
    fullTitle: 'Hot Tub, Spa, Pool & Jacuzzi Wiring',
    description: 'Our team of experienced professionals can help you get your new hot tub up and running in no time.',
    longDescription: 'Hot tubs, spas, pools, and jacuzzis require dedicated electrical circuits and specialized wiring to operate safely. These high-power installations demand 240V service, proper GFCI protection, and specific disconnect requirements. Our electricians are experts in aquatic electrical installations, ensuring your backyard water feature is wired safely and up to code.',
    image: '/images/Hot_Tub_Pool_Jacuzzi_Wiring-Service-Image.webp',
    features: [
      '240V hot tub wiring',
      'GFCI disconnect installation',
      'Spa panel installation',
      'Pool pump wiring',
      'Equipment bonding',
      'Permit and inspection handling',
      'Load calculation services',
      'Panel upgrades if needed',
    ],
    benefits: [
      'Ensures safe operation',
      'Meets all electrical codes',
      'Prevents electrical hazards',
      'Proper voltage for equipment',
      'Professional permit handling',
    ],
    process: [
      { step: 1, title: 'Site Evaluation', description: 'We assess your panel capacity and plan the electrical route.' },
      { step: 2, title: 'Permitting', description: 'We obtain all necessary electrical permits.' },
      { step: 3, title: 'Installation', description: 'We install dedicated circuits, disconnects, and all wiring.' },
      { step: 4, title: 'Inspection', description: 'We schedule and pass the required electrical inspection.' },
    ],
    faqs: [
      { question: 'What electrical requirements does a hot tub need?', answer: 'Most hot tubs require a dedicated 240V, 50-60 amp circuit with a GFCI-protected disconnect within sight of the tub.' },
      { question: 'Can my electrical panel handle a hot tub?', answer: 'We\'ll assess your panel capacity. Many homes need a panel upgrade to safely add a hot tub circuit.' },
      { question: 'How far can the disconnect be from the hot tub?', answer: 'The disconnect must be at least 5 feet from the water but within line of sight, typically no more than 50 feet away.' },
    ],
  },
  'new-construction': {
    id: 'new-construction',
    category: 'Electrician',
    title: 'New Construction',
    fullTitle: 'New Construction Electrical Services',
    description: 'The team at Westek is your best choice for your new construction wiring and electrical needs.',
    longDescription: 'Building a new home is exciting, and the electrical system is one of the most critical components to get right. Our new construction electrical services cover everything from initial design and load calculations to rough-in wiring, panel installation, and final trim-out. We work closely with builders and homeowners to create electrical systems that meet today\'s needs and tomorrow\'s demands.',
    image: '/images/New_Construction-Service-Image.webp',
    features: [
      'Complete electrical system design',
      'Load calculations and planning',
      'Rough-in wiring installation',
      'Panel and meter installation',
      'Fixture and device trim-out',
      'Smart home pre-wiring',
      'EV charger rough-in',
      'Home theater and audio wiring',
    ],
    benefits: [
      'Custom designed for your needs',
      'Built to exceed code requirements',
      'Future-proofed for technology',
      'Coordinated with other trades',
      'Single point of accountability',
    ],
    process: [
      { step: 1, title: 'Design', description: 'We work with you and your builder to plan the complete electrical system.' },
      { step: 2, title: 'Rough-In', description: 'We install all wiring, boxes, and panels before walls are closed.' },
      { step: 3, title: 'Trim-Out', description: 'After drywall, we install all outlets, switches, and fixtures.' },
      { step: 4, title: 'Final', description: 'We complete testing, labeling, and obtain final inspection approval.' },
    ],
    faqs: [
      { question: 'When should I contact an electrician for new construction?', answer: 'Contact us during the planning phase so we can coordinate with your builder and ensure the design meets all your electrical needs.' },
      { question: 'Can you pre-wire for future needs?', answer: 'Absolutely. We recommend pre-wiring for EV chargers, home theaters, security systems, and smart home technology during construction.' },
      { question: 'Do you work with all builders?', answer: 'Yes, we work with custom home builders, production builders, and owner-builders throughout Southern California.' },
    ],
  },
  'dedicated-circuits': {
    id: 'dedicated-circuits',
    category: 'Additions',
    title: 'Dedicated Circuits',
    fullTitle: 'Dedicated Circuit Installation',
    description: 'Need an extra circuit for your home? Westek can help. We offer dedicated circuits for homes of all sizes.',
    longDescription: 'Many modern appliances and equipment require their own dedicated circuits to operate safely and efficiently. A dedicated circuit ensures that high-power devices have adequate electrical supply without overloading shared circuits. Our electricians install dedicated circuits for everything from kitchen appliances to home offices, workshops, and EV chargers.',
    image: '/images/Dedicated-Circuit-Service-Image.webp',
    features: [
      'Kitchen appliance circuits',
      'Home office circuits',
      'HVAC dedicated circuits',
      'Workshop and garage circuits',
      'EV charger circuits',
      'Medical equipment circuits',
      'Home theater circuits',
      'Sump pump circuits',
    ],
    benefits: [
      'Prevents circuit overloading',
      'Eliminates nuisance tripping',
      'Ensures appliance performance',
      'Meets code requirements',
      'Improves electrical safety',
    ],
    process: [
      { step: 1, title: 'Assessment', description: 'We evaluate your panel capacity and circuit requirements.' },
      { step: 2, title: 'Planning', description: 'We determine the optimal route and circuit specifications.' },
      { step: 3, title: 'Installation', description: 'We install the new breaker, wiring, and outlet or connection.' },
      { step: 4, title: 'Testing', description: 'We verify proper voltage, grounding, and circuit function.' },
    ],
    faqs: [
      { question: 'What appliances need dedicated circuits?', answer: 'Refrigerators, microwaves, dishwashers, garbage disposals, washers, dryers, HVAC systems, and any appliance over 1000 watts typically need dedicated circuits.' },
      { question: 'How do I know if I need a dedicated circuit?', answer: 'If an appliance trips breakers frequently or causes lights to dim when running, it likely needs its own dedicated circuit.' },
      { question: 'Can you add circuits if my panel is full?', answer: 'Yes, we can install tandem breakers where code allows, or upgrade your panel to accommodate additional circuits.' },
    ],
  },
  'landscape-lighting': {
    id: 'landscape-lighting',
    category: 'Outdoor',
    title: 'Landscape Lighting',
    fullTitle: 'Landscape Lighting Installation',
    description: 'Westek Electric Corp. is the professional\'s choice for landscaping wiring.',
    longDescription: 'Professional landscape lighting transforms your outdoor spaces into stunning nighttime environments while improving safety and security. Our landscape lighting experts design and install systems that highlight architectural features, illuminate pathways, and create ambiance throughout your property. We use high-quality LED fixtures and low-voltage systems for energy efficiency and longevity.',
    image: '/images/Lanscape-Lighting-Service-Image.webp',
    features: [
      'Path and walkway lighting',
      'Uplighting for trees and architecture',
      'Garden and flower bed lighting',
      'Water feature illumination',
      'Deck and patio accent lights',
      'Low-voltage transformer installation',
      'Smart landscape controls',
      'Timer and photocell setup',
    ],
    benefits: [
      'Dramatic curb appeal enhancement',
      'Improved nighttime safety',
      'Extended outdoor enjoyment',
      'Increased property value',
      'Energy-efficient LED operation',
    ],
    process: [
      { step: 1, title: 'Design Consultation', description: 'We walk your property and design a custom lighting plan.' },
      { step: 2, title: 'Installation', description: 'We install transformers, run wiring, and place fixtures.' },
      { step: 3, title: 'Adjustment', description: 'We fine-tune fixture positions and aim for optimal effect.' },
      { step: 4, title: 'Programming', description: 'We set up timers and controls for automatic operation.' },
    ],
    faqs: [
      { question: 'Is low-voltage landscape lighting safe?', answer: 'Yes, low-voltage (12V) landscape lighting is very safe and can even be handled while powered on without risk of shock.' },
      { question: 'How much does landscape lighting cost?', answer: 'Costs vary based on property size and complexity. We provide free estimates tailored to your specific project.' },
      { question: 'Can landscape lighting be expanded later?', answer: 'Absolutely. We design systems with future expansion in mind, making it easy to add fixtures as your landscape evolves.' },
    ],
  },
}

export const COMMERCIAL_SERVICE_DETAILS: Record<string, ServiceDetail> = {
  '1-phase-3-phase': {
    id: '1-phase-3-phase',
    category: 'Circuit Additions',
    title: '1 Phase / 3 Phase Circuits',
    fullTitle: '1 Phase & 3 Phase Circuit Installation',
    description: 'Need to add a new circuit to your home or office with ease? Westek\'s electricians have you covered.',
    longDescription: 'Understanding the difference between single-phase and three-phase power is crucial for commercial operations. Single-phase power is standard for most applications, while three-phase power is essential for heavy machinery, large HVAC systems, and industrial equipment. Our commercial electricians expertly install and upgrade both types of circuits to meet your business\'s power demands.',
    image: '/images/1-Phase-3-Phase-Service-Image.webp',
    features: [
      'Single-phase circuit installation',
      'Three-phase power setup',
      'Phase conversion solutions',
      'Load balancing services',
      'Commercial panel upgrades',
      'Motor and equipment circuits',
      'High-voltage installations',
      'Power quality analysis',
    ],
    benefits: [
      'Supports heavy equipment operation',
      'Improves power efficiency',
      'Reduces electrical costs',
      'Enables business expansion',
      'Meets industrial power needs',
    ],
    process: [
      { step: 1, title: 'Power Analysis', description: 'We assess your current power setup and future needs.' },
      { step: 2, title: 'Engineering', description: 'We design the optimal circuit configuration for your equipment.' },
      { step: 3, title: 'Installation', description: 'Our commercial team installs all wiring, panels, and connections.' },
      { step: 4, title: 'Commissioning', description: 'We test and verify all circuits under load conditions.' },
    ],
    faqs: [
      { question: 'When do I need three-phase power?', answer: 'Three-phase is needed for large motors (over 5 HP), commercial HVAC systems, industrial equipment, and high-power machinery.' },
      { question: 'Can you convert single-phase to three-phase?', answer: 'Yes, we can install phase converters or coordinate with the utility for true three-phase service installation.' },
      { question: 'Is three-phase more expensive?', answer: 'While installation costs more, three-phase power is more efficient for heavy loads, often reducing operating costs.' },
    ],
  },
  'breakers-fuses': {
    id: 'breakers-fuses',
    category: 'Commercial',
    title: 'Breakers & Fuses',
    fullTitle: 'Commercial Breakers & Fuses',
    description: 'Westek provides expert installation and replacement of commercial breakers in your business.',
    longDescription: 'Commercial electrical systems require robust protection through properly sized and maintained breakers and fuses. Our commercial electricians service all types of commercial panels, from small retail breaker boxes to large industrial switchgear. We handle emergency repairs, scheduled replacements, and system upgrades to keep your business powered and protected.',
    image: '/images/Commercial-Breakers-Fuses-Service-Image.webp',
    features: [
      'Commercial breaker replacement',
      'Fuse panel servicing',
      'Main breaker upgrades',
      'Switchgear maintenance',
      'Arc flash protection',
      'Emergency repairs',
      'Preventive maintenance',
      'Panel labeling and documentation',
    ],
    benefits: [
      'Minimizes business downtime',
      'Prevents electrical fires',
      'Ensures code compliance',
      'Protects expensive equipment',
      'Improves system reliability',
    ],
    process: [
      { step: 1, title: 'Inspection', description: 'We thoroughly inspect your electrical protection systems.' },
      { step: 2, title: 'Analysis', description: 'We identify issues and recommend appropriate solutions.' },
      { step: 3, title: 'Service', description: 'Our team performs replacements and repairs with minimal disruption.' },
      { step: 4, title: 'Documentation', description: 'We update panel schedules and provide service records.' },
    ],
    faqs: [
      { question: 'How often should commercial breakers be inspected?', answer: 'Commercial electrical systems should be inspected annually, with more frequent checks for critical systems.' },
      { question: 'Should I replace fuses with breakers?', answer: 'In many cases, yes. Circuit breakers are more convenient and safer. We can evaluate your system and recommend options.' },
      { question: 'Can you work during business hours?', answer: 'Yes, we can schedule work during off-hours or coordinate to minimize disruption to your operations.' },
    ],
  },
  'code-corrections': {
    id: 'code-corrections',
    category: 'Commercial',
    title: 'Code Corrections',
    fullTitle: 'Commercial Code Corrections',
    description: 'We\'re the experts in commercial wiring code corrections. Let us help you stay compliant and safe.',
    longDescription: 'Commercial properties face strict electrical code requirements that are regularly updated. Whether you\'ve received a violation notice, are preparing for an inspection, or want to proactively ensure compliance, our commercial electricians identify and correct code violations efficiently. We understand the unique requirements for different commercial occupancies and help you maintain a safe, compliant facility.',
    image: '/images/Commercial-Code-Corrections-Service-Image.webp',
    features: [
      'Code violation assessments',
      'Fire marshal compliance',
      'ADA electrical compliance',
      'Emergency lighting upgrades',
      'Exit sign installation',
      'GFCI/AFCI upgrades',
      'Panel and wiring corrections',
      'Permit and inspection coordination',
    ],
    benefits: [
      'Avoids fines and penalties',
      'Maintains business licenses',
      'Reduces liability exposure',
      'Ensures employee safety',
      'Facilitates property transactions',
    ],
    process: [
      { step: 1, title: 'Assessment', description: 'We conduct a comprehensive code compliance inspection.' },
      { step: 2, title: 'Report', description: 'We provide a detailed report with prioritized corrections.' },
      { step: 3, title: 'Remediation', description: 'Our team performs all necessary code corrections.' },
      { step: 4, title: 'Verification', description: 'We coordinate inspections and provide compliance documentation.' },
    ],
    faqs: [
      { question: 'What triggers a commercial electrical inspection?', answer: 'Inspections may be triggered by complaints, permit applications, business license renewals, property sales, or insurance requirements.' },
      { question: 'How quickly can you address code violations?', answer: 'We offer expedited services for urgent violations. Most corrections can be completed within days of assessment.' },
      { question: 'Do you handle permit applications?', answer: 'Yes, we handle all permitting and coordinate with inspectors on your behalf.' },
    ],
  },
  'panel-installation': {
    id: 'panel-installation',
    category: 'Commercial',
    title: 'Electrical Panel Installation',
    fullTitle: 'Commercial Electrical Panel Installation',
    description: 'Westek is a full-service electrical contractor, providing expert installation of commercial electrical panels.',
    longDescription: 'Commercial electrical panels are the heart of your business\'s power distribution system. Whether you\'re building new, expanding operations, or upgrading outdated equipment, our commercial electricians design and install panel systems that meet your current needs and allow for future growth. We work with all major panel manufacturers and handle projects from small retail to large industrial.',
    image: '/images/Commercial-Electric-Panel-Installation-Service-Image.webp',
    features: [
      'Main distribution panels',
      'Sub-panel installation',
      'Panel capacity upgrades',
      'Switchboard installation',
      'Load center replacement',
      'Metering equipment',
      'Generator transfer switches',
      'Surge protection systems',
    ],
    benefits: [
      'Supports business growth',
      'Improves power reliability',
      'Meets code requirements',
      'Enables new equipment',
      'Reduces maintenance issues',
    ],
    process: [
      { step: 1, title: 'Load Analysis', description: 'We calculate your current and projected power requirements.' },
      { step: 2, title: 'Design', description: 'We design a panel system with appropriate capacity and features.' },
      { step: 3, title: 'Installation', description: 'Our team installs panels with minimal disruption to operations.' },
      { step: 4, title: 'Commissioning', description: 'We test, label, and document the complete system.' },
    ],
    faqs: [
      { question: 'How do I know if I need a panel upgrade?', answer: 'Signs include frequently tripped breakers, inability to add circuits, panel age over 25 years, or plans to add major equipment.' },
      { question: 'Can you install panels without shutting down my business?', answer: 'In many cases, yes. We can install new panels and transfer circuits in phases to maintain power during the upgrade.' },
      { question: 'What size panel do I need?', answer: 'Panel size depends on your current and future power needs. We perform load calculations to determine the optimal size.' },
    ],
  },
  'new-construction': {
    id: 'new-construction',
    category: 'Wiring',
    title: 'New Construction',
    fullTitle: 'Commercial New Construction Wiring',
    description: 'We\'re the experts in wiring new construction. Let us help you get your project up and running smoothly.',
    longDescription: 'Commercial new construction projects require electrical contractors who understand the unique demands of business facilities. From retail stores and restaurants to office buildings and warehouses, our team has the experience to deliver complete electrical systems on time and within budget. We coordinate with general contractors, architects, and other trades to ensure seamless project completion.',
    image: '/images/Cmmercial-Wiring-New-Construction-Service-Image.webp',
    features: [
      'Complete electrical system design',
      'Commercial power distribution',
      'Lighting system installation',
      'Data and communication wiring',
      'Fire alarm rough-in',
      'Security system wiring',
      'Energy management systems',
      'Code compliance assurance',
    ],
    benefits: [
      'Turnkey electrical solutions',
      'On-time project completion',
      'Budget-conscious execution',
      'Single point of contact',
      'Long-term reliability',
    ],
    process: [
      { step: 1, title: 'Pre-Construction', description: 'We review plans and coordinate with the project team.' },
      { step: 2, title: 'Rough-In', description: 'We install all conduit, wiring, and boxes during construction.' },
      { step: 3, title: 'Trim', description: 'We install devices, fixtures, and equipment after finishes.' },
      { step: 4, title: 'Commissioning', description: 'We test all systems and obtain final approvals.' },
    ],
    faqs: [
      { question: 'Do you work with our general contractor?', answer: 'Yes, we coordinate closely with GCs, architects, and other trades to ensure smooth project flow.' },
      { question: 'Can you help with electrical design?', answer: 'Absolutely. We offer design-build services and can work from architectural drawings or help develop electrical plans.' },
      { question: 'What types of commercial projects do you handle?', answer: 'We handle all commercial types including retail, office, restaurant, warehouse, medical, and light industrial.' },
    ],
  },
  'outdoor-lighting': {
    id: 'outdoor-lighting',
    category: 'Outdoor',
    title: 'Commercial Lighting',
    fullTitle: 'Commercial Outdoor Lighting',
    description: 'The team at Westek offers a variety of wiring solutions for your commercial lighting needs.',
    longDescription: 'Commercial outdoor lighting serves critical functions for safety, security, and brand visibility. Our commercial lighting experts design and install parking lot lights, building-mounted fixtures, sign lighting, and landscape illumination. We focus on energy-efficient LED solutions that reduce operating costs while providing excellent visibility and security.',
    image: '/images/Commercial-ourdoor-lighting-Service-Image.webp',
    features: [
      'Parking lot lighting',
      'Building exterior lighting',
      'Sign and monument lighting',
      'Walkway and entry lighting',
      'Security lighting systems',
      'LED retrofit programs',
      'Photocell and timer controls',
      'Emergency lighting',
    ],
    benefits: [
      'Improves customer safety',
      'Enhances property security',
      'Reduces energy costs',
      'Increases visibility',
      'Meets code requirements',
    ],
    process: [
      { step: 1, title: 'Site Assessment', description: 'We evaluate your property and lighting requirements.' },
      { step: 2, title: 'Design', description: 'We create a lighting plan meeting codes and your objectives.' },
      { step: 3, title: 'Installation', description: 'Our team installs all fixtures with minimal business disruption.' },
      { step: 4, title: 'Optimization', description: 'We adjust and program controls for optimal performance.' },
    ],
    faqs: [
      { question: 'How much can I save with LED parking lot lights?', answer: 'LED retrofits typically reduce lighting energy costs by 50-75% while improving light quality and reducing maintenance.' },
      { question: 'Are there rebates for commercial lighting upgrades?', answer: 'Yes, many utilities offer rebates for LED upgrades. We can help identify and apply for available incentives.' },
      { question: 'How do you handle tall pole lights?', answer: 'We have bucket trucks and equipment to service pole-mounted fixtures of all heights safely and efficiently.' },
    ],
  },
  'indoor-lighting': {
    id: 'indoor-lighting',
    category: 'Indoor',
    title: 'Commercial Lighting',
    fullTitle: 'Commercial Indoor Lighting',
    description: 'We have provided quality commercial indoor lighting installation for businesses for over 15 years.',
    longDescription: 'Proper indoor lighting is essential for employee productivity, customer experience, and energy efficiency. Our commercial lighting team installs and upgrades lighting systems for offices, retail stores, warehouses, and industrial facilities. We specialize in LED solutions that provide superior light quality while dramatically reducing energy consumption and maintenance costs.',
    image: '/images/Commercial-Indoor-Lighting-Service-Image.webp',
    features: [
      'Office lighting systems',
      'Retail display lighting',
      'Warehouse high-bay lighting',
      'Manufacturing lighting',
      'LED panel installation',
      'Troffer replacement',
      'Dimming and controls',
      'Emergency lighting',
    ],
    benefits: [
      'Improves employee productivity',
      'Enhances retail displays',
      'Reduces energy costs 50-75%',
      'Decreases maintenance',
      'Meets lighting codes',
    ],
    process: [
      { step: 1, title: 'Assessment', description: 'We evaluate current lighting and identify improvement opportunities.' },
      { step: 2, title: 'Proposal', description: 'We provide options with ROI calculations and payback periods.' },
      { step: 3, title: 'Installation', description: 'Our team installs new lighting with minimal operational impact.' },
      { step: 4, title: 'Verification', description: 'We measure light levels and verify energy savings.' },
    ],
    faqs: [
      { question: 'How disruptive is a lighting upgrade?', answer: 'Most upgrades can be done during off-hours or in phases to minimize disruption to your operations.' },
      { question: 'What is the payback period for LED lighting?', answer: 'Most commercial LED upgrades pay for themselves in 1-3 years through energy and maintenance savings.' },
      { question: 'Can you improve light quality in our space?', answer: 'Yes, modern LED fixtures offer superior color rendering and distribution compared to older fluorescent lighting.' },
    ],
  },
  'security-lighting': {
    id: 'security-lighting',
    category: 'Commercial',
    title: 'Security Lighting',
    fullTitle: 'Commercial Security Lighting',
    description: 'Don\'t let your business be a target. Protect it with commercial security lighting from Westek.',
    longDescription: 'Effective security lighting is one of the most cost-effective crime deterrents for commercial properties. Our security lighting solutions illuminate vulnerable areas, eliminate hiding spots, and integrate with your overall security system. We design coverage plans that protect your property while minimizing energy consumption and light pollution.',
    image: '/images/Commercial-Security-Lighting-Service-Image.webp',
    features: [
      'Motion-activated floodlights',
      'Building perimeter lighting',
      'Loading dock illumination',
      'Dumpster area lighting',
      'Camera-compatible lighting',
      'Emergency egress lighting',
      'Vandal-resistant fixtures',
      'Smart lighting controls',
    ],
    benefits: [
      'Deters criminal activity',
      'Enhances surveillance effectiveness',
      'Improves employee safety',
      'Reduces insurance costs',
      'Protects assets',
    ],
    process: [
      { step: 1, title: 'Security Assessment', description: 'We identify vulnerable areas and lighting gaps.' },
      { step: 2, title: 'Design', description: 'We create a comprehensive security lighting plan.' },
      { step: 3, title: 'Installation', description: 'Our team installs all fixtures and controls.' },
      { step: 4, title: 'Integration', description: 'We coordinate with security systems for optimal coverage.' },
    ],
    faqs: [
      { question: 'Does security lighting really prevent crime?', answer: 'Yes, studies show that proper lighting can reduce crime by up to 20% by eliminating shadows and increasing visibility.' },
      { question: 'How do you coordinate with security cameras?', answer: 'We work with your security provider to ensure lighting supports camera performance without creating glare or blind spots.' },
      { question: 'What about light pollution and neighbors?', answer: 'We use shielded fixtures and careful aiming to illuminate your property without creating problems for neighbors.' },
    ],
  },
  'transformers': {
    id: 'transformers',
    category: 'Installation',
    title: 'Transformers',
    fullTitle: 'Commercial Transformer Installation',
    description: 'We are professional electrical contracting company that specializes in the installation of commercial transformers.',
    longDescription: 'Commercial and industrial operations often require transformers to convert utility power to usable voltages for equipment and machinery. Our electricians are experienced in installing, maintaining, and replacing transformers of all sizes. We ensure proper sizing, installation, and grounding to maximize efficiency and safety for your facility.',
    image: '/images/Commercial-Transformer-Installation-Service-Image.webp',
    features: [
      'Dry-type transformer installation',
      'Step-down transformers',
      'Isolation transformers',
      'Buck-boost transformers',
      'Three-phase transformers',
      'Transformer maintenance',
      'Oil testing and analysis',
      'Replacement services',
    ],
    benefits: [
      'Proper voltage for equipment',
      'Improved power quality',
      'Reduced equipment damage',
      'Enhanced efficiency',
      'Reliable operation',
    ],
    process: [
      { step: 1, title: 'Load Analysis', description: 'We calculate your transformer requirements based on equipment needs.' },
      { step: 2, title: 'Specification', description: 'We specify the correct transformer type, size, and features.' },
      { step: 3, title: 'Installation', description: 'Our team installs the transformer with proper ventilation and access.' },
      { step: 4, title: 'Commissioning', description: 'We test and verify transformer operation under load.' },
    ],
    faqs: [
      { question: 'How do I know what size transformer I need?', answer: 'Transformer sizing depends on your connected load. We calculate kVA requirements based on your equipment specifications.' },
      { question: 'What\'s the difference between dry-type and oil-filled transformers?', answer: 'Dry-type transformers are safer for indoor use and require less maintenance. Oil-filled are typically used outdoors for larger loads.' },
      { question: 'How often do transformers need maintenance?', answer: 'We recommend annual inspections, with more frequent checks for critical systems. Oil-filled units need periodic oil testing.' },
    ],
  },
  'office-lighting': {
    id: 'office-lighting',
    category: 'Commercial',
    title: 'Office Lighting',
    fullTitle: 'Office Lighting Solutions',
    description: 'Improve the productivity and comfort of your employees with our commercial office lighting solutions.',
    longDescription: 'Office lighting directly impacts employee productivity, comfort, and well-being. Our office lighting solutions combine energy efficiency with human-centric design principles to create work environments that support focus and reduce eye strain. We upgrade outdated fluorescent systems to modern LED solutions that provide better light quality while cutting energy costs.',
    image: '/images/Commercial-Office-Lighting-Service-Image.webp',
    features: [
      'LED panel installations',
      'Troffer upgrades',
      'Task lighting solutions',
      'Conference room lighting',
      'Daylight integration',
      'Dimming controls',
      'Occupancy sensors',
      'Tunable white lighting',
    ],
    benefits: [
      'Increases productivity',
      'Reduces eye strain',
      'Cuts energy costs',
      'Improves employee comfort',
      'Creates professional atmosphere',
    ],
    process: [
      { step: 1, title: 'Workplace Assessment', description: 'We evaluate current lighting and workspace requirements.' },
      { step: 2, title: 'Design', description: 'We create a lighting plan optimized for your work environment.' },
      { step: 3, title: 'Installation', description: 'We upgrade lighting with minimal disruption to work.' },
      { step: 4, title: 'Fine-tuning', description: 'We adjust and program controls for optimal comfort and efficiency.' },
    ],
    faqs: [
      { question: 'How does lighting affect productivity?', answer: 'Studies show proper lighting can increase productivity by 5-15% while reducing headaches and eye strain.' },
      { question: 'What color temperature is best for offices?', answer: 'Generally 4000-5000K provides a neutral to cool white that promotes alertness without being harsh.' },
      { question: 'Can you install lighting during business hours?', answer: 'Yes, we can work in phases or during less busy periods to minimize disruption.' },
    ],
  },
  'low-voltage-wiring': {
    id: 'low-voltage-wiring',
    category: 'Commercial',
    title: 'Low Voltage Wiring',
    fullTitle: 'Commercial Low Voltage Wiring',
    description: 'Low-voltage wiring is a critical part of any security system. Let the experts at Westek handle it for you.',
    longDescription: 'Low voltage systems are essential for modern commercial operations, supporting security cameras, access control, fire alarms, and communication networks. Our low voltage wiring specialists install clean, organized infrastructure that performs reliably and allows for future expansion. We work with all major security and communication system brands.',
    image: '/images/Commercial-Low-Voltage-Wiring-Service-Image.webp',
    features: [
      'Security camera wiring',
      'Access control systems',
      'Intercom and paging',
      'Fire alarm wiring',
      'Audio/visual systems',
      'Structured cabling',
      'Cable management',
      'Testing and certification',
    ],
    benefits: [
      'Supports security systems',
      'Enables communication',
      'Allows future expansion',
      'Professional appearance',
      'Reliable performance',
    ],
    process: [
      { step: 1, title: 'Planning', description: 'We design the low voltage infrastructure based on your system needs.' },
      { step: 2, title: 'Pathway Installation', description: 'We install conduit, cable trays, and pathways.' },
      { step: 3, title: 'Cable Installation', description: 'We pull, terminate, and label all cables.' },
      { step: 4, title: 'Testing', description: 'We test and certify all connections for proper performance.' },
    ],
    faqs: [
      { question: 'Can low voltage wiring be installed in existing buildings?', answer: 'Yes, we can add low voltage wiring to any building using existing pathways or installing new routes.' },
      { question: 'Is low voltage wiring different from electrical wiring?', answer: 'Yes, low voltage typically operates under 50V and has different installation requirements than line voltage electrical.' },
      { question: 'Do you install the security systems too?', answer: 'We focus on wiring infrastructure and can coordinate with security system integrators for complete solutions.' },
    ],
  },
  'cat6-installation': {
    id: 'cat6-installation',
    category: 'Installation',
    title: 'Cat 6 Installation',
    fullTitle: 'Category 6 Network Cabling Installation',
    description: 'We offer Category 6 wiring for your home or business. Call Westek Electric Corp. today for a quote.',
    longDescription: 'In today\'s connected business environment, reliable network infrastructure is essential. Category 6 cabling provides the bandwidth and reliability needed for modern data, voice, and video applications. Our certified technicians install structured cabling systems that meet industry standards and support current and future networking needs.',
    image: '/images/Commercial-Cat6-Installation-Service-Image.webp',
    features: [
      'Cat6 and Cat6A installation',
      'Patch panel installation',
      'Wall jack installation',
      'Cable management systems',
      'Network rack setup',
      'Testing and certification',
      'Cable labeling',
      'As-built documentation',
    ],
    benefits: [
      'Gigabit network speeds',
      'Reliable data transmission',
      'Future-proof infrastructure',
      'Professional installation',
      'Warranty backed',
    ],
    process: [
      { step: 1, title: 'Site Survey', description: 'We assess your space and networking requirements.' },
      { step: 2, title: 'Design', description: 'We create a structured cabling plan for your needs.' },
      { step: 3, title: 'Installation', description: 'We install all cabling, terminations, and management.' },
      { step: 4, title: 'Certification', description: 'We test every run and provide certification documentation.' },
    ],
    faqs: [
      { question: 'What\'s the difference between Cat5e and Cat6?', answer: 'Cat6 supports faster speeds (up to 10 Gbps at shorter distances) and has better resistance to interference than Cat5e.' },
      { question: 'Should I install Cat6 or Cat6A?', answer: 'Cat6A supports 10 Gbps at longer distances and is recommended for future-proofing, though Cat6 is sufficient for most current needs.' },
      { question: 'Do you provide cable testing?', answer: 'Yes, we test and certify every cable run using professional certification equipment and provide documentation.' },
    ],
  },
}

// Helper function to get service by ID
export function getResidentialServiceById(id: string): ServiceDetail | undefined {
  return RESIDENTIAL_SERVICE_DETAILS[id]
}

export function getCommercialServiceById(id: string): ServiceDetail | undefined {
  return COMMERCIAL_SERVICE_DETAILS[id]
}

// Get all service IDs for static generation
export function getAllResidentialServiceIds(): string[] {
  return Object.keys(RESIDENTIAL_SERVICE_DETAILS)
}

export function getAllCommercialServiceIds(): string[] {
  return Object.keys(COMMERCIAL_SERVICE_DETAILS)
}
